project_urls:
    Source Code: https://sylvainprigent.github.io/napari-tracks-reader
    Project Site: https://sylvainprigent.github.io/napari-tracks-reader/
    Documentation: https://sylvainprigent.github.io/napari-tracks-reader/description.html
    Bug Tracker: https://github.com/sylvainprigent/napari-tracks-reader/issues
    User Support: https://github.com/sylvainprigent/napari-tracks-reader/issues
    Twitter: https://twitter.com/SylvainPrigent2